generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JobeetCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          jobeet_category_category
    with_doctrine_route:     1

    config:
      actions: ~
      fields:  ~
      list:    
        title: Category Management
        display: [=name, slug]
        batch_actions: {}
        object_actions: {}
      filter:  ~
      form:    ~
      edit:    
        title: Editing Category "%%name%%"
      new:     
        title: New Category
